import { CommonConstants } from '../../common/constants/CommonConstants'

@Preview
@CustomDialog
export default struct UserPrivacyDialog {
  // 声明一个控制器
  private controller: CustomDialogController

  // 同意
  private confirm: () => void

  // 不同意
  private cancel: () => void

  build() {

    Column({ space: CommonConstants.SPACE_10 }) {

      // 1.标题
      Text($r('app.string.user_privacy_title'))
        .fontSize(18)
        .margin({ top: 10 })
        .fontWeight(CommonConstants.FONT_WEIGHT_700)

      // 2.内容
      Text($r('app.string.user_privacy_content'))
        .fontSize(16)

      Button($r('app.string.agree_label'))
        .width(150)
        .backgroundColor($r('app.color.primary_color'))
        .fontColor(Color.White)
        .onClick(() => {
          this.confirm()
          this.controller.close()
        })

      Button($r('app.string.refuse_label'))
        .width(150)
        .backgroundColor($r('app.color.lightest_primary_color'))
        .fontColor($r('app.color.light_gray'))
        .onClick(() => {
          this.cancel()
          this.controller.close()
        })
    }.width('100%')
    .padding(10)

  }
}